### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by Karma824** [alexlyee/massdm#9]
Unhandled promise rejection: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/Users/akram/Desktop/massdm-master/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (/Users/akram/Desktop/massdm-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:390:10)
    at WebSocket.onClose (/Users/akram/Desktop/massdm-master/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at /Users/akram/Desktop/massdm-master/node_modules/ws/lib/websocket.js:220:12
    at Receiver.cleanup (/Users/akram/Desktop/massdm-master/node_modules/ws/lib/receiver.js:535:15)
    at WebSocket.finalize (/Users/akram/Desktop/massdm-master/node_modules/ws/lib/websocket.js:206:20)

**Comment by Karma824** [comment]
I have all those dependencies installed too

**Comment by alexlyee** [comment]
"Incorrect login details were provided" you have created the bot incorrectly.
